### ISSUE TITLE
Moir´e and aliasing Metric?

### ISSUE THREAD

**Issue by Minotaur-CN** [mgharbi/demosaicnet_torch#1]
hi,
Thanks for your amazing work for demosaic.
I write the moire metric just like your Siggraph paper, but it doesn't work for many scenes.
Here is my py code for your reference. Thanks!

	 img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2LAB)
	 img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2LAB)
	 res_img_final = np.zeros(img1.shape)
	 for i in range(3):
		dft1 = cv2.dft(np.float32(img1[:, :, i]), flags=cv2.DFT_COMPLEX_OUTPUT)
		dft_shift1 = np.fft.fftshift(dft1)

		dft2 = cv2.dft(np.float32(img2[:, :, i]), flags=cv2.DFT_COMPLEX_OUTPUT)
		dft_shift2 = np.fft.fftshift(dft2)
		eps = 1e-8
		magnitude_spectrum1 = np.log(cv2.magnitude(dft_shift1[:, :, 0], dft_shift1[:, :, 1]) + eps)
		magnitude_spectrum2 = np.log(cv2.magnitude(dft_shift2[:, :, 0], dft_shift2[:, :, 1]) + eps)

		res_img = magnitude_spectrum1 - magnitude_spectrum2
		res_img_tmp = np.ones(res_img.shape)
		a = res_img[int(0.05 * res_img.shape[0]): int(0.95 * res_img.shape[0]),
					int(0.05 * res_img.shape[1]): int(0.95 * res_img.shape[1])]
		res_img_tmp[int(0.05 * res_img.shape[0]): int(0.95 * res_img.shape[0]),
					int(0.05 * res_img.shape[1]): int(0.95 * res_img.shape[1])] = a
		res_img = cv2.GaussianBlur(res_img_tmp, (3, 3), 0)
		# ret, thresh_img = cv2.threshold(res_img, thres, thres, cv2.THRESH_BINARY)
		res_img_final[:, :, i] = res_img
	 max_channel = np.max(res_img_final, axis=2)

**Comment by mgharbi** [comment]
Hi, 

The metric we used to capture moiré-prone patterns was not intended to be exact, nor exhaustive. In particular, I confirm that it may lead to a few false positives. 

A good way to debug your implementation it to check that the metrics fires on the patches from our 'moiré' dataset.

One difference I can see is that you use cv2.magnitude, we used the squared magnitude in Eq (7), and r=0.95*np.pi not 0.95

**Comment by Minotaur-CN** [comment]
Hi mgharbi,
Thanks for your reply!

1. the metric FrequencyGain p(w)=log(F0(w)^2/F1(w)^2) equals to log(abs(F0(w)/F1(w)))=log(abs(F0(w))-log(abs(F1(w)), cause log(F0(w)^2)=2*log(abs(F0(w))), So I thought cv2.magnitude should be ok for your Eq(7).

2, low-pass radius i may be not correctly understood as your paper.
3. How to classify pathes as moir'e patch, threshold channel max by 2? and what's next? sum all the none zero pixel? or add the threshed moir'e probility?

Could u share your this part of the code (Moir′e and aliasing) to help my evalution?

Thanks you very much!


BR,

**Comment by Minotaur-CN** [comment]
Dear mgharbi,
Can u share the moire and vdp dataset used for training in your paper?

Thanks!

**Comment by mgharbi** [comment]
Sure, but the factor matters or you should adjust the threshold accordingly.

The data is here: https://groups.csail.mit.edu/graphics/demosaicnet/

I unfortunately did not keep the code for this part.

**Comment by Minotaur-CN** [comment]
Thanks for your kindly reply!
^.^
