### ISSUE TITLE
Missing LaplacianFilter in demosaic/loss.py?

### ISSUE THREAD

**Issue by Minotaur-CN** [mgharbi/demosaicnet_torch#3]
Dear mgharbi,
@mgharbi 
Missing LaplacianFilter in demosaic/loss.py. Please the torchlib in this repo

Thanks!

**Comment by mgharbi** [comment]
Hi, I do not intend to support the torch version of the code. You probably do not need the LaplacianFilter anyways. But I am afraid you're on your own if you decide to use this repo.
